spring:
  jpa:
    hibernate:
      ddl-auto: none
  #      dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://cmu-17647-hw2-databasereplicainstance-tarvjn8jk2lz.crvoqcxxien2.us-east-1.rds.amazonaws.com/Scalable_A1
    username: sylviahw2
    password: Zyp980211
